config/routes.rb
GoList::Application.routes.draw do
  get "go_lists/show"
  resources :listed_restaurants

  devise_for :users
  resources :restaurants
  root to: 'go_lists#show'

  get 'search_yelp' => 'go_lists#search_yelp'
  get 'add-to-list' => 'go_lists#add'

end

app/models/listed_restaurant.rb
class ListedRestaurant < ActiveRecord::Base
	belongs_to :user
	belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :listed_restaurants
  has_many :users, through: :listed_restaurants, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :listed_restaurants
  has_many :restaurants, through: :listed_restaurants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/go_lists_controller.rb
class GoListsController < ApplicationController

  def show
    if user_signed_in?
      @user = User.find( current_user.id )
    end
  end

  def search_yelp
    if params[:term] && params[:location]
      config          = YAML::load(File.open("#{Rails.root}/config/settings.local.yml"))
      api_host        = 'api.yelp.com'

      consumer        = OAuth::Consumer.new(config['yelp']['consumer_key'], config['yelp']['consumer_secret'], {:site => "http://#{api_host}"})
      access_token    = OAuth::AccessToken.new(consumer, config['yelp']['token'], config['yelp']['token_secret'])

      path            = '/v2/search?term=' + params[:term] + '&location=' + params[:location]

      render text: access_token.get(path).body
    
    else
      render :file => 'public/404.html', :status => :not_found, :layout => false
    end
  end

  def add
    if params[:restaurantID]
      user = User.find( current_user.id )
      
      restaurant = Restaurant.find_by data: params[:restaurantID]
      if !restaurant
        restaurant = Restaurant.create( name: params[:name], location: "test loc", data: params[:restaurantID] )
      end

      user.listed_restaurants.create(restaurant: restaurant)
      render text: "Success"
    else
      render :file => 'public/404.html', :status => :not_found, :layout => false
    end
  end
end

app/controllers/listed_restaurants_controller.rb
class ListedRestaurantsController < ApplicationController
  before_action :set_listed_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /listed_restaurants
  # GET /listed_restaurants.json
  def index
    @listed_restaurants = ListedRestaurant.all
  end

  # GET /listed_restaurants/1
  # GET /listed_restaurants/1.json
  def show
  end

  # GET /listed_restaurants/new
  def new
    @listed_restaurant = ListedRestaurant.new
  end

  # GET /listed_restaurants/1/edit
  def edit
  end

  # POST /listed_restaurants
  # POST /listed_restaurants.json
  def create
    @listed_restaurant = ListedRestaurant.new(listed_restaurant_params)

    respond_to do |format|
      if @listed_restaurant.save
        format.html { redirect_to @listed_restaurant, notice: 'Listed restaurant was successfully created.' }
        format.json { render action: 'show', status: :created, location: @listed_restaurant }
      else
        format.html { render action: 'new' }
        format.json { render json: @listed_restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listed_restaurants/1
  # PATCH/PUT /listed_restaurants/1.json
  def update
    respond_to do |format|
      if @listed_restaurant.update(listed_restaurant_params)
        format.html { redirect_to @listed_restaurant, notice: 'Listed restaurant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @listed_restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listed_restaurants/1
  # DELETE /listed_restaurants/1.json
  def destroy
    @listed_restaurant.destroy
    respond_to do |format|
      format.html { redirect_to listed_restaurants_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listed_restaurant
      @listed_restaurant = ListedRestaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listed_restaurant_params
      params[:listed_restaurant]
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render action: 'show', status: :created, location: @restaurant }
      else
        format.html { render action: 'new' }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :location, :data)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/go_lists_helper.rb
module GoListsHelper
end

app/helpers/listed_restaurants_helper.rb
module ListedRestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/go_lists/show.html.erb
<h1>GoList</h1>
<input class="search-yelp" />
<div class="results"></div>

<% if user_signed_in? %>
  <section class="go-list">
  <% @user.listed_restaurants.each do |restaurant| %>
    <p><%= restaurant.restaurant.name %></p>
  <% end %>
  </section>

<% else %>
  <p>Not logged in.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>GoList</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>

		<% if user_signed_in? %>
			<%= link_to current_user.email, edit_user_registration_path %>
			<%= link_to "Log Out", destroy_user_session_path, method: :delete %>
		<% else %>
			<%= link_to "Register", new_user_registration_path %>
			<%= link_to "Log in", new_user_session_path %>
		<% end %>

		<p class="notice"><%= notice %></p>
	  <p class="alert"><%= alert %></p>

		<%= yield %>

	</body>
</html>

app/views/listed_restaurants/_form.html.erb
<%= simple_form_for(@listed_restaurant) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/listed_restaurants/edit.html.erb
<h1>Editing listed_restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @listed_restaurant %> |
<%= link_to 'Back', listed_restaurants_path %>

app/views/listed_restaurants/index.html.erb
<h1>Listing listed_restaurants</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @listed_restaurants.each do |listed_restaurant| %>
      <tr>
        <td><%= link_to 'Show', listed_restaurant %></td>
        <td><%= link_to 'Edit', edit_listed_restaurant_path(listed_restaurant) %></td>
        <td><%= link_to 'Destroy', listed_restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listed restaurant', new_listed_restaurant_path %>

app/views/listed_restaurants/new.html.erb
<h1>New listed_restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', listed_restaurants_path %>

app/views/listed_restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_listed_restaurant_path(@listed_restaurant) %> |
<%= link_to 'Back', listed_restaurants_path %>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name %>
  <%= f.input :location %>
  <%= f.input :data %>
  
  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Listing restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Data</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.location %></td>
        <td><%= restaurant.data %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @restaurant.location %>
</p>

<p>
  <strong>Data:</strong>
  <%= @restaurant.data %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>